services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: unless-stopped

  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    depends_on:
      - qdrant
    ports:
      - "7860:7860"
    environment:
      - PORT=7860
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
    volumes:
      - ./data/.flowise:/data/.flowise
      - ./data/uploads:/data/uploads
    command: >
      sh -lc "mkdir -p /data/.flowise/logs /data/uploads && \
              flowise start --PORT 7860 --DATABASE_PATH /data/.flowise --LOG_PATH /data/.flowise/logs"
    restart: unless-stopped
